## EXERCISES

### Vector Multiplication
1. Produce 2 vectors, one with integers in the range [5,10] and the other [15,20] using the np.arange function
1. Without using any functions from the numpy module
    1. Compute the outer product of those vectors 
    1. Compute the "trace" of the resulting matrix
    
    ![trace](https://wikimedia.org/api/rest_v1/media/math/render/svg/3e5b6e82272fc5eeca6d510388e0a2bd0a6c6463)
    
    
Complete the same items using numpy operations

In [1]:
import numpy as np
x = np.arange(5,11)
y = np.arange(15,21)
print(x, '\n', y)

[ 5  6  7  8  9 10] 
 [15 16 17 18 19 20]


### A

In [21]:
p_out = [] # initialize empty list

assert (len(x)==len(y)), 'Lists must be the same length!'

for i in range(len(x)): # iterate through indicies of vectors
    row = [] # initialize sub list
    for j in range(len(y)):
        row.append(x[i]*y[j])
    p_out.append(row)
    
print("outer product:")
p_out

outer product:


[[75, 80, 85, 90, 95, 100],
 [90, 96, 102, 108, 114, 120],
 [105, 112, 119, 126, 133, 140],
 [120, 128, 136, 144, 152, 160],
 [135, 144, 153, 162, 171, 180],
 [150, 160, 170, 180, 190, 200]]

### B

In [44]:
trace_items = []
for i in range(len(p_out)):
    #print(i)
    #print(p_out[i][i])
    trace_items.append(p_out[i][i])

#print(trace_items)

Trace = sum(trace_items)
print(Trace)

805


### Matrix Multiplication
* Two matricies can be multiplied if their inner dimensions match (eg. 2x3 * 3x5 -> 2x5). The best rule for working with and mutliplying matricies is to remember (rows x columns). This applies to both the dimensions of a matrix (a 2x3 matrix has 2 rows and 3 columns) as well as multiplication (you multiply the rows of the first matrix by the columns of the second). 

* When multiplying two matricies of dimension (M x N)*(N x P) the resulting matrix is (M x P). The upper element of the reslting matrix is the inner (or dot) product of the first row of the first matrix and the first column of the second matrix

![two matrices](https://wikimedia.org/api/rest_v1/media/math/render/svg/16b1644351bc2041175b19cbc65da03ef78130c7)

![store product in matrix C](https://wikimedia.org/api/rest_v1/media/math/render/svg/00ac0c831c365b7424cc43239aae8cebea27c56c)

![matrix multiply](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)

for i = 1, ..., n and j = 1, ..., p.

1. Make two matrices of random numbers (A and B). A should be a 4x3 matrix and B should be a 3x4 matrix. Multiply A by B using (to a resulting matrix C) using:
    1. a conventional for-loop
    1. list comprehension
    1. numpy operator
    
2. After you have C, pull out the upper quadrant using fancy indexing, and then replace the main diagonal (upper left to lower right) with 0s. 

In [51]:
A = np.random.rand(4,3) 
B = np.random.rand(3,4)
print(A, '\n\n',B)

[[0.85974034 0.38515975 0.28491394]
 [0.09702714 0.9192704  0.08068817]
 [0.50826794 0.85571357 0.09733994]
 [0.13546569 0.50816368 0.42402412]] 

 [[0.85130136 0.35138091 0.96080839 0.5926285 ]
 [0.03836892 0.56987483 0.90097537 0.24547372]
 [0.776647   0.74714454 0.27046054 0.60632017]]


In [102]:
#A
C_A = np.zeros(16).reshape(4,4) # initialize empty list
#print(C_A)

for i in range(np.shape(A)[0]): # iterate through indicies of vectors
    for j in range(np.shape(B)[1]):
        C_A[i,j] = A[i,:].dot(B[:,j])
C_A
# print('Inner Product: %d' %sum(C_A)) # Print Output

array([[0.96795385, 0.73446109, 1.25012316, 0.7768023 ],
       [0.18053698, 0.61824828, 0.94328744, 0.33208064],
       [0.54112077, 0.73897228, 1.28565156, 0.57028843],
       [0.46413688, 0.65399706, 0.70268132, 0.46211604]])

In [78]:
#B
C_B = np.zeros(16).reshape(4,4) # initialize empty list
C_B = [[ A[i,:].dot(B[:,j]) for j in range(4)] for i in range(4) ]
np.array(C_B)

#c_out = [[x1[i]*x2[j] for j in range(len(x2))]for i in range(len(x1))]

array([[0.96795385, 0.73446109, 1.25012316, 0.7768023 ],
       [0.18053698, 0.61824828, 0.94328744, 0.33208064],
       [0.54112077, 0.73897228, 1.28565156, 0.57028843],
       [0.46413688, 0.65399706, 0.70268132, 0.46211604]])

In [116]:
#C
C_C = A.dot(B)
C_C

array([[0.96795385, 0.73446109, 1.25012316, 0.7768023 ],
       [0.18053698, 0.61824828, 0.94328744, 0.33208064],
       [0.54112077, 0.73897228, 1.28565156, 0.57028843],
       [0.46413688, 0.65399706, 0.70268132, 0.46211604]])

In [117]:
C = C_C.copy()
upper_q = C[:2,:2]
print(upper_q)
print('\n')

#print(np.diagonal(C_C))
#print(C_C.diagonal())

for k in range(len(C)):
    C[k,k] = 0
print(C)

#C_C.diagonal() = 0
print('\n')
print(C_C)

[[0.96795385 0.73446109]
 [0.18053698 0.61824828]]


[[0.         0.73446109 1.25012316 0.7768023 ]
 [0.18053698 0.         0.94328744 0.33208064]
 [0.54112077 0.73897228 0.         0.57028843]
 [0.46413688 0.65399706 0.70268132 0.        ]]


[[0.96795385 0.73446109 1.25012316 0.7768023 ]
 [0.18053698 0.61824828 0.94328744 0.33208064]
 [0.54112077 0.73897228 1.28565156 0.57028843]
 [0.46413688 0.65399706 0.70268132 0.46211604]]
